
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { BrainIcon, TrendingUpIcon, TrendingDownIcon, AlertCircleIcon, AwardIcon } from "lucide-react";

const AiInsights = () => {
  // In a real application, these insights would be generated by an AI
  const insights = [
    {
      type: "strength",
      title: "Strong Subject Lines",
      description: "Your subject lines with 5-7 words have 28% higher open rates.",
      icon: <AwardIcon className="h-5 w-5 text-green-500" />,
    },
    {
      type: "trend-up",
      title: "Increasing Engagement",
      description: "Your Tuesday emails show consistently improving open rates (↑ 3.2%).",
      icon: <TrendingUpIcon className="h-5 w-5 text-green-500" />,
    },
    {
      type: "trend-down",
      title: "Declining Click Rates",
      description: "Button clicks have dropped by 2.1% over the last 5 campaigns.",
      icon: <TrendingDownIcon className="h-5 w-5 text-red-500" />,
    },
    {
      type: "alert",
      title: "Unsubscribe Spike",
      description: "Your March 15 campaign had a 0.5% unsubscribe rate, 3x your average.",
      icon: <AlertCircleIcon className="h-5 w-5 text-amber-500" />,
    },
  ];

  return (
    <Card className="col-span-4 lg:col-span-2">
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle>
          <div className="flex items-center">
            <BrainIcon className="mr-2 h-5 w-5 text-primary" />
            AI Insights
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {insights.map((insight, i) => (
            <div key={i} className="flex space-x-3 border-l-2 border-primary pl-3">
              <div className="mt-0.5">{insight.icon}</div>
              <div>
                <h4 className="font-medium">{insight.title}</h4>
                <p className="text-sm text-muted-foreground">{insight.description}</p>
              </div>
            </div>
          ))}
          <div className="pt-2">
            <p className="text-sm text-primary">See 8 more insights →</p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default AiInsights;
