
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { BrainIcon, TrendingUpIcon, TrendingDownIcon, AlertCircleIcon, AwardIcon, BadgePercentIcon } from "lucide-react";

const AiInsights = () => {
  // In a real application, these insights would be generated by an AI based on benchmark comparisons
  const insights = [
    {
      type: "strength",
      title: "Above-Average Open Rates",
      description: "Your 23.4% open rate is 10.4% above industry average (21.2%), suggesting effective subject lines.",
      icon: <AwardIcon className="h-5 w-5 text-green-500" />,
      metric: "Open Rate",
    },
    {
      type: "trend-up",
      title: "Strong Click-Through Rate",
      description: "Your 3.8% CTR exceeds industry average (2.6%) by 46%, placing you in the top 30% of performers.",
      icon: <TrendingUpIcon className="h-5 w-5 text-green-500" />,
      metric: "Click-Through Rate",
    },
    {
      type: "trend-down",
      title: "Concerning Bounce Rate",
      description: "Your 2.1% bounce rate is double the industry average (1.0%). List cleaning recommended.",
      icon: <TrendingDownIcon className="h-5 w-5 text-red-500" />,
      metric: "Bounce Rate",
    },
    {
      type: "alert",
      title: "Spam Complaint Risk",
      description: "Spam rate (0.02%) is higher than industry benchmark (0.01%). Review frequency and segmentation.",
      icon: <AlertCircleIcon className="h-5 w-5 text-amber-500" />,
      metric: "Spam Complaints",
    },
    {
      type: "opportunity",
      title: "Revenue Growth Potential",
      description: "While above average ($0.42 vs $0.35), you're at 49% of top performers' revenue per email ($0.85).",
      icon: <BadgePercentIcon className="h-5 w-5 text-blue-500" />,
      metric: "Revenue per Email",
    },
  ];

  return (
    <Card className="col-span-4 lg:col-span-2">
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle>
          <div className="flex items-center">
            <BrainIcon className="mr-2 h-5 w-5 text-primary" />
            Benchmark-Based Insights
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {insights.map((insight, i) => (
            <div key={i} className="flex space-x-3 border-l-2 border-primary pl-3">
              <div className="mt-0.5">{insight.icon}</div>
              <div>
                <h4 className="font-medium">{insight.title}</h4>
                <p className="text-sm text-muted-foreground">{insight.description}</p>
                <p className="text-xs text-primary mt-1">Metric: {insight.metric}</p>
              </div>
            </div>
          ))}
          <div className="pt-2">
            <p className="text-sm text-primary">See 5 more benchmark insights →</p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default AiInsights;
