
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Check, Lightbulb } from "lucide-react";

const RecommendationList = () => {
  // In a real application, these recommendations would be generated by an AI
  const recommendations = [
    {
      title: "Optimize Send Times",
      description: "Your data shows that emails sent between 9-11am have 17% higher open rates. Consider adjusting your campaign schedule.",
      priority: "high",
    },
    {
      title: "Segment Your Audience",
      description: "Subscribers who clicked on product links engage 3x more. Create a dedicated segment for these high-interest users.",
      priority: "high",
    },
    {
      title: "Revise CTA Copy",
      description: "Direct CTAs like 'Shop Now' outperform 'Click Here' by 24%. Update your CTA language in upcoming campaigns.",
      priority: "medium",
    },
    {
      title: "Personalize Subject Lines",
      description: "Emails with name personalization have 15% higher open rates. Add personalization tokens to your next campaign.",
      priority: "medium",
    },
  ];

  return (
    <Card className="col-span-4 lg:col-span-2">
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle>
          <div className="flex items-center">
            <Lightbulb className="mr-2 h-5 w-5 text-primary" />
            Recommendations
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {recommendations.map((rec, i) => (
            <div
              key={i}
              className={`flex gap-2 p-3 rounded-md ${
                rec.priority === "high" ? "bg-amber-50 border-amber-100" : "bg-blue-50 border-blue-100"
              }`}
            >
              <div className="shrink-0 w-5 h-5 mt-0.5">
                <div className={`h-5 w-5 rounded-full flex items-center justify-center ${
                  rec.priority === "high" ? "bg-amber-100" : "bg-blue-100"
                }`}>
                  <Check className="h-3 w-3 text-primary" />
                </div>
              </div>
              <div>
                <h4 className="font-medium text-sm">{rec.title}</h4>
                <p className="text-xs text-muted-foreground mt-1">{rec.description}</p>
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
};

export default RecommendationList;
